steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/intent-detection-agent/intent-frontend:latest'
      - '-f'
      - 'Dockerfile.frontend'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=https://intent-backend-584414482857.asia-south1.run.app'
      - '.'
images: ['gcr.io/intent-detection-agent/intent-frontend:latest']
timeout: '1200s'
