version: "3.9"

services:
  neo4j:
    image: neo4j:5.23  # use latest stable 5.x
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"   # Neo4j Browser (HTTP)
      - "7687:7687"   # Bolt protocol (driver/API access)
    environment:
      NEO4J_AUTH: neo4j/password123  # username: neo4j, password: password123
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_dbms_security_procedures_allowlist: apoc.*
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/import:/import

  qdrant:
    image: qdrant/qdrant:latest  # stable release
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"   # HTTP API
      - "6334:6334"   # gRPC API
    volumes:
      - ./qdrant/storage:/qdrant/storage


