version: '3.8'

services:
  neo4j:
    image: neo4j:5.15
    container_name: intent-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    networks:
      - intent-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: intent-qdrant
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # GRPC
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - intent-network

  redis:
    image: redis:7-alpine
    container_name: intent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - intent-network

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
  qdrant_data:
  redis_data:

networks:
  intent-network:
    driver: bridge
