embedding:
  batch_size: 32
  max_concurrent_processing: 10
  model_name: all-MiniLM-L6-v2
  model_type: sentence_transformer
  openai_api_key: ''
log_level: INFO
metrics_enabled: true
neo4j_password: password
neo4j_uri: bolt://localhost:7687
neo4j_user: neo4j
qdrant:
  collection_name: signals
  embedding_dimension: 384
  host: localhost
  max_results: 1000
  port: 6333
  similarity_threshold: 0.8
sources:
  executives:
    api_keys: {}
    cache_ttl: 3600
    custom_headers: {}
    enabled: true
    requests_per_minute: 30
    retry_attempts: 3
    retry_backoff_factor: 2.0
    timeout: 30
    user_agent: EDI-Graph/1.0
  funding:
    api_keys: {}
    cache_ttl: 3600
    custom_headers: {}
    enabled: true
    requests_per_minute: 30
    retry_attempts: 3
    retry_backoff_factor: 2.0
    timeout: 30
    user_agent: EDI-Graph/1.0
  jobs:
    api_keys:
      adzuna_id: f43c1731
      adzuna_key: 191194e59ff0acc60c84c18e8e5909b7
    cache_ttl: 7200
    custom_headers: {}
    enabled: true
    requests_per_minute: 60
    retry_attempts: 3
    retry_backoff_factor: 2.0
    timeout: 45
    user_agent: EDI-Graph/1.0
  news:
    api_keys:
      newsapi: a12518d30bb549f1a9bea1264509009b
    cache_ttl: 7200
    custom_headers:
      Accept: application/json
    enabled: true
    requests_per_minute: 45
    retry_attempts: 3
    retry_backoff_factor: 2.0
    timeout: 30
    user_agent: EDI-Graph/1.0
  tech:
    api_keys: {}
    cache_ttl: 1800
    custom_headers: {}
    enabled: true
    requests_per_minute: 60
    retry_attempts: 3
    retry_backoff_factor: 2.0
    timeout: 30
    user_agent: EDI-Graph/1.0
