steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/intent-detection-agent/intent-backend:latest'
      - '-f'
      - '.deployment/Dockerfile.backend'
      - '.'
images:
  - 'gcr.io/intent-detection-agent/intent-backend:latest'
timeout: '1200s'
